.\" Manpage for WebPhonon
.\" Contact aaron.zakhrov@gmail.com to correct errors or typos.
.TH man 1 "4 February 2016" "2.0" "WebPhonon man page"
.SH NAME
WebPhonon \- A Phonon based media player and media library manager
.SH SYNOPSIS
WebPhonon [URL]
.SH DESCRIPTION
WebPhonon is a simple Phonon based media player and media library manager. It provides a clean interface for video playback and has a library manager with XBMC like features. Currently works with only MySQL/MariaDB databases
.SH OPTIONS
.TP
.BR
--help \- Show help about options
.TP
.BR
--licensce \- prints the licence agreement
.TP
.BR
-v --version \- prints version information
.TP
.BR
.SH SEE ALSO
WebPhonon(1)
.SH BUGS
Still in its beta stages. There may be ocassional crashes and not all features have been implemented
MSSQL Server/ODBC support currently broken
No Support for Sqlite or other embedded DBs
Still relies on the Phonon DirectShow backend on Windows

.SH AUTHOR
Aaron Dominick (aaron.zakhrov@gmail.com)